"use client";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import Menu from "./(components)/menu";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };
export default function RootLayout({ children }) {
	let currentRoute = usePathname();
	return (
		<html lang="en">
			<body className={inter.className}>
				<ul>
					<li>
						<Link
							className={currentRoute === "/csr" ? "greenmenu" : "blackmenu"}
							href="/csr"
						>
							csr
						</Link>
					</li>
					<li>
						<Link
							className={currentRoute === "/ssr" ? "greenmenu" : "blackmenu"}
							href="/ssr"
						>
							ssr
						</Link>
					</li>
				</ul>
				<Menu />
				{children}
				<ProgressBar
				// height="4px"
				// color="#fffd00"
				// options={{ showSpinner: false }}
				// shallowRouting
				/>
			</body>
		</html>
	);
}
